---
on:
  push:
    branches:
      - "main"

jobs:
  "build":
    runs-on: "ubuntu-latest"

    permissions:
      contents: "write"

    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - uses: "actions/setup-java@v3"
        with:
          java-version: "17"
          distribution: "temurin"
          settings-path: "${{ github.workspace }}"

      - shell: "bash"
        run: "./build.sh"
